name: CI-CD Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Build Docker image
    run: docker build -t 192.168.0.75:5000/k8s-runtime-ci:1.0 ./app

  - name: Login to registry
    run: docker login 192.168.0.75:5000 -u admin -p admin

  - name: Push image
    run: docker push 192.168.0.75:5000/k8s-runtime-ci:1.0

  - name: Setup kubeconfig
    run: |
      mkdir -p ~/.kube
      echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

  - name: Restart deployment
    run: kubectl rollout restart deployment k8s-runtime-ci
